services:
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    configs:
      - source: init.sql
        target: /docker-entrypoint-initdb.d/init.sql

  postgrest:
    image: postgrest/postgrest:v12.2.3
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@postgres:5432/postgres
      PGRST_DB_ANON_ROLE: postgres
    depends_on:
      - postgres

volumes:
  postgres-data:

configs:
  init.sql:
    content: |
      CREATE EXTENSION vector;

      CREATE TABLE docs (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

        title VARCHAR(255),
        location VARCHAR(255),
        content TEXT,

        embedding vector(768)
      );

      CREATE OR REPLACE FUNCTION find_similar_docs(query_embedding vector, limit_count int DEFAULT 5)
      RETURNS SETOF docs AS $$$$
      BEGIN
        RETURN QUERY
        SELECT *
        FROM docs
        ORDER BY embedding <-> query_embedding
        LIMIT limit_count;
      END;
      $$$$ LANGUAGE plpgsql;