# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tool_pb2 as tool__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tool_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ToolStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Tools = channel.unary_unary(
                '/tool.Tool/Tools',
                request_serializer=tool__pb2.ToolsRequest.SerializeToString,
                response_deserializer=tool__pb2.ToolsResponse.FromString,
                _registered_method=True)
        self.Execute = channel.unary_unary(
                '/tool.Tool/Execute',
                request_serializer=tool__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=tool__pb2.ResultResponse.FromString,
                _registered_method=True)


class ToolServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Tools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToolServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Tools': grpc.unary_unary_rpc_method_handler(
                    servicer.Tools,
                    request_deserializer=tool__pb2.ToolsRequest.FromString,
                    response_serializer=tool__pb2.ToolsResponse.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=tool__pb2.ExecuteRequest.FromString,
                    response_serializer=tool__pb2.ResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tool.Tool', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tool.Tool', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Tool(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Tools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tool.Tool/Tools',
            tool__pb2.ToolsRequest.SerializeToString,
            tool__pb2.ToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tool.Tool/Execute',
            tool__pb2.ExecuteRequest.SerializeToString,
            tool__pb2.ResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
