services:
  platform:
    image: adrianliechti/llama-platform
    pull_policy: always
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    configs:
      - source: platform
        target: /config.yaml
  
  web:
    image: adrianliechti/llama-streamlit
    pull_policy: always
    ports:
      - 8501:8501
    environment:
      - OPENAI_BASE_URL=http://platform:8080/oai/v1
    depends_on:
      - platform
  
configs:
  platform:
    content: |
      providers:
        - type: azure-translator
          token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
          url: https://xxxxxxxx.cognitiveservices.azure.com/
          models:
            english-translator:
              id: en
            german-translator:
              id: de
