version: "3"

services:
  llama:
    image: ghcr.io/ggerganov/llama.cpp:full
    pull_policy: always
    command: --server --host 0.0.0.0 --port 8000 --path /public --model /models/llama-2-7b-chat.Q4_K_M.gguf --embedding --alias default
    volumes:
      - ./models:/models:cached

  gateway:
    image: adrianliechti/llama-openai:2
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: always
    ports:
      - 8080:8080
    configs:
      - source: config
        target: /config.yaml
  
  web:
    image: ghcr.io/mckaywrigley/chatbot-ui:main
    pull_policy: always
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_KEY=changeme
      - OPENAI_API_HOST=http://gateway:8080
      - DEFAULT_MODEL=gpt-3.5-turbo
  
configs:
  config:
    content: |
      auth:
        token: changeme

      providers:
        - type: llama
          url: http://llama:8000
          models:
            gpt-3.5-turbo:
              id: default
              template: llama