version: "3"

services:
  model:
    image: curlimages/curl
    pull_policy: always
    command: > 
      /bin/ash -c "
      if [ ! -f /models/mistral-7b-instruct-v0.2.Q4_K_M.gguf ]; then
        echo Downloading Model...
        curl -s -L -o /models/mistral-7b-instruct-v0.2.Q4_K_M.gguf https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GGUF/resolve/main/mistral-7b-instruct-v0.2.Q4_K_M.gguf
      fi"
    volumes:
      - ./models:/models:cached
             
  llama:
    image: ghcr.io/ggerganov/llama.cpp:full
    pull_policy: always
    command: --server --host 0.0.0.0 --port 8080 --model /models/mistral-7b-instruct-v0.2.Q4_K_M.gguf --alias mistral
    volumes:
      - ./models:/models:cached
    depends_on:
      model:
        condition: service_completed_successfully
  
  sentence-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    pull_policy: always
    environment:
      ENABLE_CUDA: 0

  gateway:
    image: adrianliechti/llama-openai:2
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: always
    ports:
      - 8080:8080
    configs:
      - source: config
        target: /config.yaml
    depends_on:
      - llama
      - sentence-transformers
  
  web:
    image: ghcr.io/mckaywrigley/chatbot-ui:main
    pull_policy: always
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_KEY=changeme
      - OPENAI_API_HOST=http://gateway:8080/oai
      - DEFAULT_MODEL=gpt-3.5-turbo
      - NEXT_PUBLIC_DEFAULT_TEMPERATURE=0.6
      - NEXT_PUBLIC_DEFAULT_SYSTEM_PROMPT=You are a helpful assistant. Follow the user's instructions carefully. Respond using markdown.
    depends_on:
      - gateway
  
configs:
  config:
    content: |
      providers:
        - type: llama
          url: http://llama:8080
          models:
            gpt-3.5-turbo:
              id: mistral
              template: mistral
        
        - type: sentence-transformers
          url: http://sentence-transformers:8080
          models:
            text-embedding-ada-002:
              id: all-minilm-l6-v2

      authorizers:
        - type: static
          token: changeme