providers:
  # - type: openai
  #   token: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

  #   models:
  #     gpt-3.5-turbo:
  #       id: gpt-3.5-turbo-1106

  #     gpt-4:
  #       id: gpt-4-1106-preview

  #     text-embedding-ada-002:
  #       id: text-embedding-ada-002

  - type: llama
    url: http://localhost:9081

    models:
      mistral:
        id: default
        template: mistral

  # - type: ollama
  #   url: http://localhost:11434

  #   models:
  #     mistral:
  #       id: mistral

  - type: sbert
    url: http://localhost:9082

    models:
      all-mpnet-base-v2:
        id: all-mpnet-base-v2

indexes:
  docs:
    # type: memory
    # embedding: all-mpnet-base-v2

    type: chroma
    url: http://localhost:9083
    namespace: docs
    embedding: all-mpnet-base-v2

    # type: weaviate
    # url: http://localhost:9084
    # namespace: Document1
    # embedding: all-mpnet-base-v2

chains:
  docs:
    type: rag
    index: docs
    model: mistral