version: "3"

services:
  platform:
    image: adrianliechti/llama-platform
    pull_policy: always
    ports:
      - 8080:8080
    configs:
      - source: config
        target: /config.yaml
  
  web:
    image: adrianliechti/llama-ui
    pull_policy: always
    ports:
      - 3000:3000
    environment:
      - OPENAI_BASE_URL=http://platform:8080/oai/v1
      - OPENAI_MODEL=mistral-7b-instruct
    depends_on:
      - platform
  
configs:
  config:
    content: |
      providers:
        - type: ollama
          url: http://host.docker.internal:11434
          models:
            mistral-7b-instruct:
              id: mistral