services:
  platform:
    image: ghcr.io/adrianliechti/llama-platform
    pull_policy: always
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    configs:
      - source: platform
        target: /config.yaml
    depends_on:
      - ollama
      - ollama-companion
  
  ollama:
    image: ollama/ollama:0.5.3
    pull_policy: always
    volumes:
      - ollama-data:/root/.ollama
  
  ollama-companion:
    image: ghcr.io/adrianliechti/ollama-companion
    pull_policy: always
    restart: on-failure
    environment:
      - OLLAMA_HOST=ollama:11434
      - OLLAMA_MODELS=llama3.2:1b,nomic-embed-text:v1.5

  web:
    image: ghcr.io/adrianliechti/llama-chat
    pull_policy: always
    ports:
      - 8000:8000
    environment:
      - OPENAI_BASE_URL=http://platform:8080/v1
    depends_on:
      - platform

configs:
  platform:
    content: |
      providers:
        - type: ollama
          url: http://ollama:11434

          # https://ollama.com/library
          models:
            llama:
              id: llama3.2:1b
            
            nomic:
              id: nomic-embed-text:v1.5

volumes:
  ollama-data: