services:
  platform:
    image: ghcr.io/adrianliechti/llama-platform
    pull_policy: always
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    configs:
      - source: platform
        target: /config.yaml
  
configs:
  platform:
    content: |
      providers:
        - type: llama
          url: http://host.docker.internal:9081
          models:
            - llama

        - type: whisper
          url: http://host.docker.internal:9083
          models:
            - whisper-1
        
        - type: openai
          url: http://host.docker.internal:9085/v1
          models:
            - tts-1