apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: server
          image: ghcr.io/adrianliechti/llama-streamlit
          imagePullPolicy: Always
          env:
            - name: OPENAI_BASE_URL
              value: http://platform/v1
          ports:
            - containerPort: 8501
          resources: {}