# https://taskfile.dev

version: '3'

vars:
  REPOSITORY: adrianliechti/llama-server

tasks:
  publish:
    cmds:
      - docker buildx build . --push --platform linux/amd64,linux/arm64 --tag {{.REPOSITORY}}:latest
      - docker buildx build cuda --push --platform linux/amd64 --tag {{.REPOSITORY}}:cuda