services:
  platform:
    image: ghcr.io/adrianliechti/llama-platform
    pull_policy: always
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    configs:
      - source: platform
        target: /config.yaml
    depends_on:
      - ollama
  
  ollama:
    image: ollama/ollama
    pull_policy: always
    volumes:
      - ollama_data:/root/.ollama

  web:
    image: ghcr.io/adrianliechti/llama-streamlit
    pull_policy: always
    ports:
      - 8501:8501
    environment:
      - OPENAI_BASE_URL=http://platform:8080/oai/v1
    depends_on:
      - platform

configs:
  platform:
    content: |
      providers:
        - type: ollama
          url: http://ollama:11434
          models:
            phi3:
              id: phi3:latest
volumes:
  ollama_data: